services:

  postgres:
    image: postgres:15
    container_name: pint-postgres
    restart: always
    environment:
      POSTGRES_DB: pintdb
      POSTGRES_USER: pintadmin
      POSTGRES_PASSWORD: pintpass
    ports:
      - "5432:5432"
    volumes:
      - pint-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: pint-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: pint-app
    depends_on:
      - postgres
      - redis

    ports:
      - "8080:8080"

volumes:
  pint-postgres-data: